version: '2'
services:
  composeapi:
    build: .
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    ports:
      - 8080:3000
    restart: always
    command: perl compose_api.pl daemon
  watcher:
    build: .
    ports:
      - 8081:3000
    restart: always
    command: perl watcher.pl daemon
    depends_on:
      - composeapi
