version: '2'
services:
  test1:
    image: ubuntu
    command: bash -c "while sleep 1; do sleep 1; done"
    scaling:
      min: 3
      max: 10
  test2:
    image: ubuntu
    command: bash -c "while sleep 1; do sleep 1; done"
    scaling:
      min: 3
      max: 10
      initial: 5
  inserter:
    image: ubuntu
    command: bash -c 'while sleep 5; do curl -i -XPOST "http://localhost:8086/write?db=fodocker" --data-binary "metric1,service=test1 value=70"; done'
metrics:
  - metric1
  - metric2
alerts:
  metric1: "<70"

#curl -XPOST -F 'file=@sample.yml' watcher:3000/test
